### ISSUE TITLE
Hazelcast Global Serialiser Notes

### ISSUE THREAD

**Issue by scottg88** [payara/Payara-Server-Documentation#235]
When Payara initialises the in-built Hazelcast instance, it overrides the global serialiser with a `PayaraHazelcastSerializer` serialiser.

I think this warrants a note in the documentation so people are aware of why a global serialiser they set will not be applied. Happy to contribute this however to clarify, is the purpose of this serialiser to let the Hazelcast EJB/Web persistence provider work?

**Comment by OndrejM** [comment]
Hi @scottg88, thanks for feedback.
We took a note to add it to the documentation.
