### ISSUE TITLE
Typo in "using password alias in JDBC Connection Pool"

### ISSUE THREAD

**Issue by dmainardi** [payara/Payara-Server-Documentation#306]
On page
https://github.com/payara/Payara-Server-Documentation/blob/master/documentation/payara-server/password-aliases/password-aliases-overview.adoc
the image
https://github.com/payara/Payara-Server-Documentation/raw/master/images/password-aliases/password-aliases-using.png
shows
`${alias=example-alias-name}`
but it should be
`${ALIAS=example-alias-name}`

**Comment by mikecroft** [comment]
Fixed by #307
