### ISSUE TITLE
API Documentation for Payara Micro is out of date

### ISSUE THREAD

**Issue by smillidge** [payara/Payara-Server-Documentation#31]
I don't think we should have the section where the methods on Payara Micro are documented. This will just get out of date, Better that the javadoc is hosted and referred to.

**Comment by mikecroft** [comment]
@smillidge I found this:
http://payara.github.io/Payara/nucleus_API/payara-modules/payara-micro/target/apidocs/

Is that kept up to date?

**Comment by smillidge** [comment]
no idea ask @Pandrex247

**Comment by OndrejM** [comment]
The javadocs don't seem to be updated: https://github.com/payara/Payara/commits/gh-pages/nucleus_API/payara-modules/payara-micro/target/apidocs/fish/payara/micro

I'll create a task to automate it.

**Comment by OndrejM** [comment]
Created private issue PAYARA-1466.

**Comment by rdebusscher** [comment]
Tracked now as CUSTCOM-169

**Comment by fturizo** [comment]
Closing this issue as the repository is being archived now and its internally tracked in JIRA.
