### ISSUE TITLE
Clarify CDI requirements for Activating JWT Authentication (MicroProfile JWT Authentication API)

### ISSUE THREAD

**Issue by rdebusscher** [payara/Payara-Server-Documentation#384]
JAX-RS application class (which has LoginConfig) is only discovered by the CDI extension when it is considered as a CDI bean.

When you have` bean-discovery-mode="annotated"` defined, it is not "found" and thus JWT Authentication is not active.

Please indicate this in the paragraph about _Activating JWT Authentication_ in the documentation https://docs.payara.fish/documentation/microprofile/jwt.html since _annotated_ mode is used very often to limit the creation of unnecessary CDI beans.

Originated from https://github.com/payara/Payara/issues/2742#issuecomment-391984004

**Comment by fturizo** [comment]
Closing this issue as the repository is being archived now and its internally tracked in JIRA. If this is still needed, @rdebusscher feel free to raise this issue again  in either community/enterprise repos.
