### ISSUE TITLE
Where to put undocumented GlassFish features

### ISSUE THREAD

**Issue by ggam** [payara/Payara-Server-Documentation#48]
I'd like to document the mecanism to register custom JACC providers, taking @arjantijms research (http://arjan-tijms.omnifaces.org/2015/01/java-ee-authorization-jacc-revisited.html) as foundation.

Currently, Payara documentation seems to hold information about "propietary" features and enhancements, and a reference to the official GlassFish documentation for common functionality. 

Since GlassFish documentation is not under our control, do you think it's ok to amplify core documentation by creating subsections? Is there a an already defined policy for this?

Thanks in advance

**Comment by mikecroft** [comment]
Hi, thanks for the PR! We will need you to sign a Contributors License Agreement (CLA) before we can accept the pull request.

We're just about to refresh the CLA itself, so I'm going to double check on the status of that so you don't have to sign it twice.

**Comment by mikecroft** [comment]
Just noticed I never properly replied to this - in case anyone else might come across it in the future, the `core-documentation` section is the correct one. Where new pages are concerned, just add them and we can move them around ourselves in future commits if we need to.
