### ISSUE TITLE
Request : dependency versions in release log

### ISSUE THREAD

**Issue by dorpsidioot** [payara/Payara-Server-Documentation#506]
The current payara release logs have a listing of the updated dependencies, but it would be nice if we also had a comprehensive list of the current dependencies, makes it easier to update pom versions to support the newer libraries. If it already exists, excuse me, haven't found it yet.

**Comment by rdebusscher** [comment]
Hi,

Versions can be found in the Payara BOM which is available since release 5.194. For example see https://search.maven.org/artifact/fish.payara.api/payara-bom/5.194/pom

Regards
Rudy.
