### ISSUE TITLE
Conflicting version numbers listed

### ISSUE THREAD

**Issue by savage-engineer** [payara/Payara-Server-Documentation#59]
In a number of files the full version number included in brackets conflicts with the short version number as can be seen here:

* [Healthcheck Service](https://github.com/payara/Payara-Server-Documentation/blob/5375f5d7713edb8eeb2c22ccdb51c308a70c480c/documentation/extended-documentation/health-check-service/health-check-service.md) 
* [SQL Trace Listeners](https://github.com/payara/Payara-Server-Documentation/blob/5375f5d7713edb8eeb2c22ccdb51c308a70c480c/documentation/extended-documentation/advanced-jdbc/sql-trace-listeners.md)

This issues seems to have arisen from the [162 version update](https://github.com/payara/Payara-Server-Documentation/commit/5375f5d7713edb8eeb2c22ccdb51c308a70c480c) commit, possibly because of conflicting documentation styles. Both of the following exist:

* "Payara Server 161 (4.1.1.162) and Payara Micro 161 introduce new capabilites for advanced JDBC connection pool configuration and diagnostics." as seen [here](https://github.com/payara/Payara-Server-Documentation/blob/5375f5d7713edb8eeb2c22ccdb51c308a70c480c/documentation/extended-documentation/advanced-jdbc/advanced-jdbc-configuration-and-diagnostics.md)
* "This page shall cover how to use the additional JBatch functionality in Payara 4.1.1.162." as seen [here](https://github.com/payara/Payara-Server-Documentation/blob/5375f5d7713edb8eeb2c22ccdb51c308a70c480c/documentation/extended-documentation/jbatch.md)

Pages where the first appears seem to usually be prefaced with "Payara Server and Micro 161 (4.1.1.162) onwards"

**Comment by mikecroft** [comment]
Resolved in `next` branch
