### ISSUE TITLE
Create global documentation conventions page

### ISSUE THREAD

**Issue by mikecroft** [payara/Payara-Server-Documentation#62]
There is a lot of repetition in pages which have sections to outline documentation conventions. These should be collated into one page.

e.g.:
https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/jbatch.html#2-documentation-conventions
https://payara.gitbooks.io/payara-server/content/documentation/extended-documentation/jcache.html#2-documentation-conventions

**Comment by fturizo** [comment]
Closing this issue as the repository is being archived now and there linked pages were already refactored.
