### ISSUE TITLE
CorsHeader option missing in set-openapi-configuration asadmin-command documentation

### ISSUE THREAD

**Issue by alexander-dammeier** [payara/Payara-Server-Documentation#638]
I searched for a possibility to add CORS headers to my openapi file. I found [this pull request](https://github.com/payara/Payara/pull/3793). 
Thats a very nice feature and its a pity that I cannot find it anywhere in your documentation.
When I looked at the pull request, I found out that it can be used in post-boot-commands as follows:
`set-openapi-configuration --corsHeaders=true`
I tested it with payara micro 5.193.1 and it works like a charm 👍 

Can you please add this to the documentation?

**Comment by OndroMih** [comment]
Hi, thanks for raising this. We added the documentation here: https://docs.payara.fish/documentation/microprofile/openapi.html#set-openapi-configuration
