### ISSUE TITLE
Documentation for arquillian-payara-server-remote connector appears to be out of date

### ISSUE THREAD

**Issue by phillipross** [payara/Payara-Server-Documentation#709]
The documentation payara-remote arquillian container has documentation for `<artifactId>arquillian-payara-server-4-remote</artifactId>` instead of `<artifactId>arquillian-payara-server-remote</artifactId>`

I've been attempting to get arquillian to deploy and test against a remote payara server running in a separate docker container but bumped into problems, and I'm not sure if I'm using the proper configuration for the connector or not.

I've filed an issue against the connector here:
https://github.com/payara/ecosystem-arquillian-connectors/issues/51

**Comment by fturizo** [comment]
Closing this issue as the repository is being archived now. Feel free to raise this issue if it still applies in the new Payara Community Documentation: https://github.com/payara/Payara-Community-Documentation
