### ISSUE TITLE
start-database utility doesn't support option --dbtype

### ISSUE THREAD

**Issue by georgeracu** [payara/Payara-Server-Documentation#732]
In the documentation for release version 5.201 is stated that Derby database can be started by using `asadmin start-database --dbtype derby`. The current version of the `start-database` utility doesn't have this option, which generates an error when trying to start Derby database.

Link to the documentation file: https://github.com/payara/Payara-Server-Documentation/blob/master/documentation/payara-server/h2/h2.adoc

Link to the actual version of the `start-database` utility: https://github.com/payara/Payara/blob/payara-server-5.201/appserver/admin/cli-optional/src/main/manpages/com/sun/enterprise/admin/cli/optional/start-database.1

**Comment by OndroMih** [comment]
Thank you for reporting this. Derby database was removed in 5.201. The `start-database` command now doesn't support the `--dbtype` option and it only starts H2 database. We need to update the documentation.
